services:
  api-gateway:
    build:
      context: ./apigateway
    ports:
      - "8080:8080"
    depends_on:
      - libros-service
      - autor-service
      - usuario-service
      - prestamos-service

  libros-service:
    build:
      context: ./libros-service
    ports:
      - "8081:8081"
    depends_on:
      - mongo
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://mongo:27017/inventariodb

  autor-service:
    build:
      context: ./autor-service
    ports:
      - "8082:8082"
    depends_on:
      - mongo
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://mongo:27017/inventariodb

  usuario-service:
    build:
      context: ./usuario-service
    ports:
      - "8084:8084"
    depends_on:
      - mongo
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://mongo:27017/inventariodb

  prestamos-service:
    build:
      context: ./prestamos-service
    ports:
      - "8085:8085"
    depends_on:
      - mongo
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://mongo:27017/inventariodb

  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
